name: Deploy Angular to IIS (Develop)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build & Deploy to IIS
    runs-on: [self-hosted, windows, iis]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Stop IIS Website
        shell: powershell
        run: |
          Import-Module WebAdministration
          Stop-WebSite -Name "myGitActions"

      - name: Deploy files to IIS
        shell: powershell
        run: |
          $source = "dist\myGitActions\browser\*"
          $destination = "C:\inetpub\wwwroot\GitActions"

          if (Test-Path $destination) {
            Remove-Item "$destination\*" -Recurse -Force
          }

          Copy-Item $source $destination -Recurse -Force

      - name: Start IIS Website
        shell: powershell
        run: |
          Import-Module WebAdministration
          Start-WebSite -Name "myGitActions"
